FROM microsoft/dotnet:1.1.1-sdk

RUN git clone https://github.com/emiladrianc/Solution

WORKDIR "/Solution/Sources/DatabaseVersioningTool/Database.VersioningTool.Tests/"

RUN dotnet restore

RUN dotnet build --no-incremental -c Release -o Binaries

RUN dotnet test -c Release -o Binaries --no-build
